# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_auto_20171116_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.ImageField(default='static/img/ava.png', upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
