# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-09 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_auto_20171209_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='upload',
            field=models.ImageField(default='static/img/ava.png', upload_to='%Y/%m/%d/'),
        ),
    ]
